exclude Intercom.xcframework files
intercom/intercom-react-native pull request #26
Opened 2021-08-25 14:28 UTC by mixail-novikov

Hello! I've faced huge warning when installing pods. You could run `pod install` in example/ios in the main branch to see the warning.

<img width="1189" alt="Screenshot 2021-08-25 at 17 22 50" src="https://user-images.githubusercontent.com/726880/130808860-f0831bd1-6f7d-418a-aac3-f070d16e0a6c.png">

I'm not an iOS developer, but this fix works for me. Could you check it?

2021-09-21 17:26 UTC, mixail-novikov commented
@bboyle18 @DaleCantwell could you review the PR? Warnings still exist in a fresh project installation.

2021-09-21 18:20 UTC, bboyle18 requested changes
By excluding `intercom.xcframework` you will exclude the intercom sdk from the project, so Intercom will not work.
From what I understand, adding `:deterministic_uuids => false` to your Podfile should solve the problem.
This is a cocoapods issue. https://github.com/CocoaPods/CocoaPods/issues/4370
Its worth reviewing solutions there that might help.

2021-09-21 18:20 UTC, bboyle18 commented
@mixail-novikov 👋 I've added a review to the PR. Cheers.

2021-10-01 13:43 UTC, closed without merging

2021-10-01 14:10 UTC, mixail-novikov commented
@bboyle18 Sorry, didn't see your response. The fix(and Intercom) working in our production app very well.

`:deterministic_uuids => false` - it's a hack, not a solution.

"Generated duplicated UUIDs" for me means that Intercom(SDK) loads several times. First time with .xcframework and second time maybe with `s.dependency "Intercom", '~> 10.0'`.

Could you spend more time finding an appropriate solution if the current one is not good? This is a real problem.

I had clean `pod install` output, and after I added intercom dependency it was polluted by these warnings. Not only for me. I checked your example and clean react-native project.

2021-10-01 15:14 UTC, bboyle18 commented
@mixail-novikov We have a fix 😄 
Will be available in the next release.