updating sdk versions for iOS and Android
intercom/intercom-react-native pull request #61
Opened 2022-04-13 15:53 UTC by niamh-coleman

- Updating to use android 12.1.1
- Updating to use iOS 12.1.0
- Adding in updated success fail callbacks ([PR](https://github.com/intercom/ios-sdk/pull/3306))
- iOS tests now use iPhone 11 
- Updated appium
- Updated RN version
- Update [circle CI docker image](https://circleci.com/developer/images/image/cimg/node)

2022-04-14 10:51 UTC, mapierce requested changes

2022-04-14 10:51 UTC, mapierce commented on ios/IntercomModule.m
> +            reject(IDENTIFIED_REGISTRATION, @"No user registered. You must supply an email, a userId or both", error);
We have error messages defined in the `ErrorProcessor` in iOS, would be good to pull them out and re-use them here so they match.

2022-04-14 10:51 UTC, mapierce commented on ios/IntercomModule.m
> +            reject(IDENTIFIED_REGISTRATION, @"No user registered. You must supply an email, a userId or both", error);
Same as above about error messages

2022-04-14 10:51 UTC, mapierce commented on ios/IntercomModule.m
> +            reject(IDENTIFIED_REGISTRATION, @"No user registered. You must supply an email, a userId or both", error);
And again about error messages

2022-04-14 10:51 UTC, mapierce commented on ios/IntercomModule.m
> +
Also need to wrap the callbacks for update user, and registering device token. And do we need to do the same for Android

2022-04-14 11:07 UTC, niamh-coleman commented on ios/IntercomModule.m
> +
I was just updating the one for now to get the feedback, so I'll make these changes and continue on with the rest if this looks okay. Thanks!

2022-04-14 11:09 UTC, mapierce commented on ios/IntercomModule.m
> +
Ah perfect. Go for it!

2022-04-21 13:58 UTC, mapierce submitted a review, later dismissed

2022-04-22 16:36 UTC, github-management-service reviewed
👋 Hey there,
It looks like your PR introduces some terminology we are trying to phase out of our codebase.
For each of the following files, we ask that you update the usage according to the [TRU Program Plan](https://docs.google.com/document/d/1IQoe6vQfGq03NiCMYhxdx2NBesgA0jcJe5ZYgMLyDSQ/edit?usp=sharing).


* example/metro.config.js, line number(s): 2


While this check doesn't block 🚢-ing, please consider making the following suggested terminology changes:
Old Usage | Updated Usage
-- | --
Whitelist (verb) | Trust
Blacklist (verb) | Block
Whitelist (noun) | Trusted list
Blacklist (noun) | Blocked list
Master (DB node) | Primary
Slave (replicated DB node) | Replica
Slave (non-replicated DB node) | Secondary




Feel free to reach out to [#tru-working-group](https://intercom.slack.com/archives/C015WCE1UQ1) with any questions.
Let me know what you end up doing after reading this:

* [ ] I addressed this comment, it’s fixed now
* [ ] I will fix in a subsequent PR
* [ ] I will keep the files as-is

2022-04-26 09:22 UTC, closed without merging